const test = require("tape");
const TreeView = require("../src/app/treeviewComponent/TreeView");

const locations = [{
    id: 0,
    text: "Massachusetts",
    children: [{
        id: 1,
        text: "Boston",
        children: [{
            id: 9,
            text: "Scituate"
        }, {
            id: 10,
            text: "Weymouth"
        }, {
            id: 11,
            text: "Abington"
        }, {
            id: 12,
            text: "Hull"
        }]
    }, {
        id: 2,
        text: "Hingham",
        children: [{
            id: 3,
            text: "Braintree",
            children: [{
                id: 5,
                text: "Southie"
            }, {
                id: 6,
                text: "Beacon Hill",
                children: [{
                    id: 13,
                    text: "Canton"
                }, {
                    id: 14,
                    text: "Marshfield"
                }, {
                    id: 15,
                    text: "Borne"
                }, {
                    id: 16,
                    text: "Sandwich"
                }]
            }, {
                id: 7,
                text: "Black Rock"
            }]
        }, {
            id: 4,
            text: "Quincy"
        }]
    }]
}];

const treeView = new TreeView({
    nodes: locations,
    expandChildren: true,
    selectedScope: 0,
    checkedLeavesArray: [15],
    highestAvailableCheckboxId: 0,
    highestPossibleScopeId: 0
});

test("test new tree view", t => {

    let treeViewJSON = treeView.toJSON();

    t.deepEqual(treeViewJSON, {
        "nodes": [{
            "id": 0,
            "text": "Massachusetts",
            "children": [{
                "id": 1,
                "text": "Boston",
                "children": [{
                    "id": 9,
                    "text": "Scituate",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 10,
                    "text": "Weymouth",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 11,
                    "text": "Abington",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 12,
                    "text": "Hull",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": false,
                "possibleToBeSelectedScope": false
            }, {
                "id": 2,
                "text": "Hingham",
                "children": [{
                    "id": 3,
                    "text": "Braintree",
                    "children": [{
                        "id": 5,
                        "text": "Southie",
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 6,
                        "text": "Beacon Hill",
                        "children": [{
                            "id": 13,
                            "text": "Canton",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 14,
                            "text": "Marshfield",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 15,
                            "text": "Borne",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": true
                        }, {
                            "id": 16,
                            "text": "Sandwich",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }],
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": true,
                        "possibleToBeSelectedScope": true
                    }, {
                        "id": 7,
                        "text": "Black Rock",
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }],
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": true,
                    "possibleToBeSelectedScope": true
                }, {
                    "id": 4,
                    "text": "Quincy",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": true,
                "possibleToBeSelectedScope": true
            }],
            "checked": false,
            "showChildren": true,
            "selectedScope": true,
            "availableCheckbox": true,
            "showNode": true,
            "ableToToggleCheckbox": true,
            "ableToToggleScope": true,
            "indeterminate": true,
            "possibleToBeSelectedScope": true
        }],
        "checkedLeavesArray": [{
            "id": 15,
            "text": "Borne"
        }],
        "uncheckedLeavesArray": [{
            "id": 9,
            "text": "Scituate"
        }, {
            "id": 10,
            "text": "Weymouth"
        }, {
            "id": 11,
            "text": "Abington"
        }, {
            "id": 12,
            "text": "Hull"
        }, {
            "id": 5,
            "text": "Southie"
        }, {
            "id": 13,
            "text": "Canton"
        }, {
            "id": 14,
            "text": "Marshfield"
        }, {
            "id": 16,
            "text": "Sandwich"
        }, {
            "id": 7,
            "text": "Black Rock"
        }, {
            "id": 4,
            "text": "Quincy"
        }],
        "selectedScope": 0,
        areAllChildrenExpanded: true,
        selectedNode: null
    });

    treeView.ToggleCheckbox(5);

    t.deepEqual(treeView.toJSON(), {
        "nodes": [{
            "id": 0,
            "text": "Massachusetts",
            "children": [{
                "id": 1,
                "text": "Boston",
                "children": [{
                    "id": 9,
                    "text": "Scituate",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 10,
                    "text": "Weymouth",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 11,
                    "text": "Abington",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 12,
                    "text": "Hull",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": false,
                "possibleToBeSelectedScope": false
            }, {
                "id": 2,
                "text": "Hingham",
                "children": [{
                    "id": 3,
                    "text": "Braintree",
                    "children": [{
                        "id": 5,
                        "text": "Southie",
                        "checked": true,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 6,
                        "text": "Beacon Hill",
                        "children": [{
                            "id": 13,
                            "text": "Canton",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 14,
                            "text": "Marshfield",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 15,
                            "text": "Borne",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 16,
                            "text": "Sandwich",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }],
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": true,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 7,
                        "text": "Black Rock",
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }],
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": true,
                    "possibleToBeSelectedScope": true
                }, {
                    "id": 4,
                    "text": "Quincy",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": true,
                "possibleToBeSelectedScope": true
            }],
            "checked": false,
            "showChildren": true,
            "selectedScope": true,
            "availableCheckbox": true,
            "showNode": true,
            "ableToToggleCheckbox": true,
            "ableToToggleScope": true,
            "indeterminate": true,
            "possibleToBeSelectedScope": true
        }],
        "checkedLeavesArray": [{
            "id": 5,
            "text": "Southie"
        }, {
            "id": 15,
            "text": "Borne"
        }],
        "uncheckedLeavesArray": [{
            "id": 9,
            "text": "Scituate"
        }, {
            "id": 10,
            "text": "Weymouth"
        }, {
            "id": 11,
            "text": "Abington"
        }, {
            "id": 12,
            "text": "Hull"
        }, {
            "id": 13,
            "text": "Canton"
        }, {
            "id": 14,
            "text": "Marshfield"
        }, {
            "id": 16,
            "text": "Sandwich"
        }, {
            "id": 7,
            "text": "Black Rock"
        }, {
            "id": 4,
            "text": "Quincy"
        }],
        "selectedScope": 0,
        areAllChildrenExpanded: true,
        selectedNode: null
    });

    treeView.ToggleCheckbox(10);

    t.deepEqual(treeView.toJSON(), {
        "nodes": [{
            "id": 0,
            "text": "Massachusetts",
            "children": [{
                "id": 1,
                "text": "Boston",
                "children": [{
                    "id": 9,
                    "text": "Scituate",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 10,
                    "text": "Weymouth",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 11,
                    "text": "Abington",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 12,
                    "text": "Hull",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": true,
                "possibleToBeSelectedScope": false
            }, {
                "id": 2,
                "text": "Hingham",
                "children": [{
                    "id": 3,
                    "text": "Braintree",
                    "children": [{
                        "id": 5,
                        "text": "Southie",
                        "checked": true,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 6,
                        "text": "Beacon Hill",
                        "children": [{
                            "id": 13,
                            "text": "Canton",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 14,
                            "text": "Marshfield",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 15,
                            "text": "Borne",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 16,
                            "text": "Sandwich",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }],
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": true,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 7,
                        "text": "Black Rock",
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }],
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": true,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 4,
                    "text": "Quincy",
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": true,
                "possibleToBeSelectedScope": false
            }],
            "checked": false,
            "showChildren": true,
            "selectedScope": true,
            "availableCheckbox": true,
            "showNode": true,
            "ableToToggleCheckbox": true,
            "ableToToggleScope": true,
            "indeterminate": true,
            "possibleToBeSelectedScope": true
        }],
        "checkedLeavesArray": [{
            "id": 10,
            "text": "Weymouth"
        }, {
            "id": 5,
            "text": "Southie"
        }, {
            "id": 15,
            "text": "Borne"
        }],
        "uncheckedLeavesArray": [{
            "id": 9,
            "text": "Scituate"
        }, {
            "id": 11,
            "text": "Abington"
        }, {
            "id": 12,
            "text": "Hull"
        }, {
            "id": 13,
            "text": "Canton"
        }, {
            "id": 14,
            "text": "Marshfield"
        }, {
            "id": 16,
            "text": "Sandwich"
        }, {
            "id": 7,
            "text": "Black Rock"
        }, {
            "id": 4,
            "text": "Quincy"
        }],
        "selectedScope": 0,
        areAllChildrenExpanded: true,
        selectedNode: null
    });

    treeView.ToggleCheckbox(6);
    treeView.ToggleCheckbox(7);
    treeView.ToggleCheckbox(4);
    treeView.ToggleCheckbox(5);
    treeView.ToggleCheckbox(11);
    treeView.ToggleCheckbox(12);
    treeView.ToggleCheckbox(9);
    treeView.ToggleCheckbox(15);

    t.deepEqual(treeView.toJSON(), {
        "nodes": [{
            "id": 0,
            "text": "Massachusetts",
            "children": [{
                "id": 1,
                "text": "Boston",
                "children": [{
                    "id": 9,
                    "text": "Scituate",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 10,
                    "text": "Weymouth",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 11,
                    "text": "Abington",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 12,
                    "text": "Hull",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": true,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": false,
                "possibleToBeSelectedScope": false
            }, {
                "id": 2,
                "text": "Hingham",
                "children": [{
                    "id": 3,
                    "text": "Braintree",
                    "children": [{
                        "id": 5,
                        "text": "Southie",
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 6,
                        "text": "Beacon Hill",
                        "children": [{
                            "id": 13,
                            "text": "Canton",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 14,
                            "text": "Marshfield",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 15,
                            "text": "Borne",
                            "checked": false,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }, {
                            "id": 16,
                            "text": "Sandwich",
                            "checked": true,
                            "showChildren": true,
                            "selectedScope": false,
                            "availableCheckbox": true,
                            "showNode": true,
                            "ableToToggleCheckbox": true,
                            "ableToToggleScope": true,
                            "indeterminate": false,
                            "possibleToBeSelectedScope": false
                        }],
                        "checked": false,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": true,
                        "possibleToBeSelectedScope": false
                    }, {
                        "id": 7,
                        "text": "Black Rock",
                        "checked": true,
                        "showChildren": true,
                        "selectedScope": false,
                        "availableCheckbox": true,
                        "showNode": true,
                        "ableToToggleCheckbox": true,
                        "ableToToggleScope": true,
                        "indeterminate": false,
                        "possibleToBeSelectedScope": false
                    }],
                    "checked": false,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": true,
                    "possibleToBeSelectedScope": false
                }, {
                    "id": 4,
                    "text": "Quincy",
                    "checked": true,
                    "showChildren": true,
                    "selectedScope": false,
                    "availableCheckbox": true,
                    "showNode": true,
                    "ableToToggleCheckbox": true,
                    "ableToToggleScope": true,
                    "indeterminate": false,
                    "possibleToBeSelectedScope": false
                }],
                "checked": false,
                "showChildren": true,
                "selectedScope": false,
                "availableCheckbox": true,
                "showNode": true,
                "ableToToggleCheckbox": true,
                "ableToToggleScope": true,
                "indeterminate": true,
                "possibleToBeSelectedScope": false
            }],
            "checked": false,
            "showChildren": true,
            "selectedScope": true,
            "availableCheckbox": true,
            "showNode": true,
            "ableToToggleCheckbox": true,
            "ableToToggleScope": true,
            "indeterminate": true,
            "possibleToBeSelectedScope": true
        }],
        "checkedLeavesArray": [{
            "id": 9,
            "text": "Scituate"
        }, {
            "id": 10,
            "text": "Weymouth"
        }, {
            "id": 11,
            "text": "Abington"
        }, {
            "id": 12,
            "text": "Hull"
        }, {
            "id": 13,
            "text": "Canton"
        }, {
            "id": 14,
            "text": "Marshfield"
        }, {
            "id": 16,
            "text": "Sandwich"
        }, {
            "id": 7,
            "text": "Black Rock"
        }, {
            "id": 4,
            "text": "Quincy"
        }],
        "uncheckedLeavesArray": [{
            "id": 5,
            "text": "Southie"
        }, {
            "id": 15,
            "text": "Borne"
        }],
        "selectedScope": 0,
        areAllChildrenExpanded: true,
        selectedNode: null
    });

    t.end();
});
